language: java
install: true
os: linux
dist: bionic
jdk: openjdk11
addons:
  apt:
    packages:
      - python3-venv
before_script:
  - export PATH="./venv/bin:$PATH"
  - export GIT_TRACE=1
  - ./scripts/before_script.sh

script:
  - "./gradlew clean assemble uploadIfNeeded deployDocsIfNeeded -i --stacktrace"

env:
  global:
    # BINTRAY
    - secure: Mx9FhkpD1IGNpCWuxxqwP+SkmPhfL8s2VmbqQC2dHCZ9oSQuCCVqhTj0Nmm1BVDYKTPk+f4OlLI8O8JKuF7pahrGd88gtRHRonwndXy6TOdxmsLcyuiFHGiKBqOY4PZSxaUYr24IrHpgoj0RlRr67eceWWSP5yv/LdRAGv0y/d/3KuRZCSg2q5rk23J7qXaoYUgH/K3Fu84u8/79UpJamiyuIxCblKPx6EY6Zp10SwLU2PUnV73zNQb1e3wgt8V9FnfNSVCz604WHEtjykWy8xdPW2jimMHGQLRnRiWCQjPMTQtHA47Vp8jWhEOYfIByRa1NCQ48DNIljZ8gg5MHB5LSpFNS/JgvuxizueluI6t04qkKwCfGBo7NDNrBrhZvSJhsQVbyMXrf0Xh53Kup0Uoyba//mNid1bJYVwNglbbxpoz3XIrfdHotDbd4XEymh3e1KnyAwoyXjmCpoms0VMLEJEwz+7QyCZLfGDlOfsEO53puGqHG4FCrx0jSvQXggv7L26Eq8vQGoYOGvVjWPNVczvN3GN5W+TKd7NoZh+mUc4wBVTiaKovdU3U/niU+OW3L95oitdfsIVH14GnKYFX1XxU5t8bsHuz71YUCRWSY8tKpyKvoX63AfTP3fv+ln6GbrczENVf53QziN4ceJoyHxh58B4kueqC/Zsll9mE=
    - secure: VnHfllieRMVg9L9iesNDuiN+YILX94iVMq5qzCVPGpQufywd2nJrRgWlxI21tk/d0BdwVxy3hLu0fb09fFBeNU27HGI3rJvDx0BjdtWb2qgHZdyWhBK5HSYnoGeCkzHTjo/Z7FewUda7Yh/5QxKLrKCgVsgqwUwrO+W9UGbYGD0PX+cWawN1INJ74+jxoG+8o+9OBQ+bleHveMTi8pVzkMQDXv1zadkenJIrZ1jh6xkSNBPZfLtfLyQ5+6ORZyEK3RZp2ZxdfldEhfb20L6YDJ0oJCDX+ao4h46hZ7nkDQml6Q5gIonUFmFvi7FZfvOGAIO0XM0+tMr9HkmEKwnMqd32tTtW7qaQevZ0ejcDOBEXecgZqXUZ6X1zg4r6HHwwBlPxBSFhAJz+IO1g9UHheiYOo9eY6Y4S4gm5JYgbHfR90jq4oznO9x6phfZD9NCSG4eew1m+oTHcXgg5ZIOwrg6riKtm9O0khsLM+OKnPzaYLPUY4Vupwsftwq+7/F5Ad8njmNGj4DOrmfq2PQNNLzajuhNbqhbeV++l6xouZP7LAC9GIIdxyzJMPguEo7p7aciQ427Hmr2SCIrI9OkULHzILOUtj/QXaqf41BkqoDnm9S2IH7bROb7cPMiH4lx7JyMOKausmjz5U5FtBSpXV5xAJB/wgpk/hClaxlyGLuw=
    # TRAVIS_KINTA_DEPLOY_KEY_KEY
    - secure: q1hh336cplj0cnbRdulV7FkIOqztFI2o7by3jc04A66XBx6snoRdt0Kt0MPOgrXNZbcDiCu3V3tmYZH1PxSb/vyH/WxiXB7UXZ8ffrU4/hsWTkRimF/4TJKhGJClvW13XeC+O1rVDk1wTmSGaOZrzXbUeCuz2ek3F6rsQTD6pEBHeF+mocSmyXpJELxby29XOvg/spo6UgbWsaXBtWLkThJdYT7kCydDrvf6qUNgAGeenlMYlEbFWgHQvHUWM+q8JzL8/FTmuEqUW/X6yYrZyur3YSxnSXmTBn05HwUsdG5544jae7oNO1xRD97cHKnlrNeyCKMBg6pC9urv/5S5y8wVDJJCJsrTbbJ6oo3HSUpKEXMhL0LoqM2jxccRaU8GE8XU61u32Kw6UFpeHP3axz74ArzS4FUEcFHmDbSyTNX1tEyFdCe8yNAIvwjYC2r1t+NaHoayJ6pxiVVK+RRpYEgyZMbNTSy+NeWCfFV230uZn5a1rKV1ZKqMgkELv1gW+1XjZnGMX1IkLXqz4yysybcIVG3nBZNaZYsUhxII+YgoIyVGlN5vZCd6fWM1KcSUE6gcxoliiObn28QhymQARSDChVuo23kIp54rBiDMjoaaC32SqQfmFOQdoMq0o7NHfdlFW90WUnYsYYXRN0/ewMUJOncl6oQN0TLfTjazTzA=
    # TRAVIS_KINTA_DEPLOY_KEY_IV
    - secure: kYEL9DAC+JASE5ilKU+20242smRfAE478BoMI55CXFgiJ0HCd5kdKvMKqIS6UnIAfEfZtmgUL/9InPZcSsvDuHN6uvPjNj+72UPojUgrOVYBF0Vzs1PaOz5rLBinah1sKMCfvNM0u2AuAiaiwPvyUCDOI/IzuWFOs/rmfpa4EfZfwpeSiwYXr0nv8bO5/mKIsC+D/m5blamXpA2AnHyZc3YEk9UJPvLw7g7ho3yExfqr+gG03AyL0z6LPo389vlRMRRF82UTM8c1NBc2nfDDDqddn7iK6+wBAdtbONcYg0IFk/hzgSZr9dD+BFOXHym6h2p1CbMlWBDrf8blxGgbYcBu3XuwUjlSsHAq7nd+HX/Zl5Ljhf34EpAwNZiQIvaNx9/QruTrVowqDm6NRsoCQNonT2pSLYsxAF93hMAo9uKEce4wfDU/n/pFWi9nPaAZOw6LyNgFkJAqiIt3/99V4ETBBwq8SSFgnrYOoVT6s4eyXEa3864sgqDfoHpwYgQMourH9TwmRKBYHBprxEtsS5snGMkgzvRRHJu44mgsZoHhEt4RqmVC42V4aPja9Tb0h958+MP8ZTBBotWvM8lKl2+Eg7I3DqD0X6e/y2BhPLsKGGABbwwb3hz0NrCYJ5bPub/rVyujGD9bYS+lWRRE/I3IsNRcxCHSL/582gE6uRk=
