name: Android CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          KINTA_GPG_PRIVATE_KEY: ${{ secrets.KINTA_GPG_PRIVATE_KEY }}
          KINTA_GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.KINTA_GPG_PRIVATE_KEY_PASSWORD }}
          KINTA_STAGING_PROFILE_ID: ${{ secrets.KINTA_STAGING_PROFILE_ID }}
        run: |
          if [ ${{ github.event_name }} != 'pull_request' ]
          then
            eval `ssh-agent -s`
            ssh-add - <<< "${{ secrets.SSH_DEPLOY_KEY }}"
            git remote set-url origin git@github.com:dailymotion/kinta.git
            git config --global user.email "apps@dailymotion.com"
            git config --global user.name "Kinta GithubActions"
            python3 -m venv venv --break-system-packages
            which pip
            pip install mkdocs-material
            mkdocs -V
          fi
          ./gradlew clean assemble deployArtifactsIfNeeded deployDocsIfNeeded deployArchivesIfNeeded -i --stacktrace
